- name: Deploy Playbook
  hosts: node1
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Copy file
      copy:
        src: /path/to/kubernetes/deploy.sh  # Correct the path if needed
        dest: /opt/deploy.sh
        remote_src: true  # Indicates the file is on the remote machine

    - name: Run Shell Script
      command: bash /opt/deploy.sh
