- name: Deploy Playbook
  host: node1
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChcking=no'
  task:
    - name: Copy file
      copy:
        src: kubernetes/deploy.sh
        dest: /opt/deploy.sh
    - name: Run Shell Script
      command: bash /opt/deploy.sh